### ISSUE TITLE
the scripts stops

### ISSUE THREAD

**Issue by Guyc1800** [itsOwen/girlfriend-morning-gn-text#4]
after I scan the qr code and it say connected the program stops
![image](https://user-images.githubusercontent.com/76709418/149659833-9376752a-ea5a-44a4-a84b-e8090109ae02.png)

**Comment by itsOwen** [comment]
npm install prompt-sync

**Comment by Guyc1800** [comment]
> npm install prompt-sync

i installed prompt-sync and it doesnt work. i looked at the code and I think it stops at the create function in line 4
![image](https://user-images.githubusercontent.com/76709418/149661407-4e904b39-2b70-4cd9-9269-d44f79f5f8d5.png)
